CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  first_month TEXT,
  last_month TEXT,
  date_format_json TEXT NOT NULL DEFAULT '{"format":"DD/MM/YYYY"}',
  currency_format_json TEXT NOT NULL DEFAULT '{"iso_code":"SGD","example_format":"$123,456.78","decimal_digits":2,"decimal_separator":".","symbol_first":true,"group_separator":",","currency_symbol":"$","display_symbol":true}',
  flag_names_json TEXT NOT NULL DEFAULT '{}',
  server_knowledge BIGINT NOT NULL DEFAULT 1,
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS accounts (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'checking',
  on_budget SMALLINT NOT NULL DEFAULT 1 CHECK (on_budget IN (0, 1)),
  closed SMALLINT NOT NULL DEFAULT 0 CHECK (closed IN (0, 1)),
  opening_balance_milli BIGINT NOT NULL DEFAULT 0,
  balance_milli BIGINT NOT NULL DEFAULT 0,
  cleared_balance_milli BIGINT NOT NULL DEFAULT 0,
  uncleared_balance_milli BIGINT NOT NULL DEFAULT 0,
  transfer_payee_id TEXT,
  direct_import_linked SMALLINT NOT NULL DEFAULT 0 CHECK (direct_import_linked IN (0, 1)),
  direct_import_in_error SMALLINT NOT NULL DEFAULT 0 CHECK (direct_import_in_error IN (0, 1)),
  include_in_net_worth SMALLINT NOT NULL DEFAULT 1 CHECK (include_in_net_worth IN (0, 1)),
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_accounts_plan_id ON accounts(plan_id);

CREATE TABLE IF NOT EXISTS category_groups (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  hidden SMALLINT NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1)),
  internal SMALLINT NOT NULL DEFAULT 0 CHECK (internal IN (0, 1)),
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_category_groups_plan_id ON category_groups(plan_id);

CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  category_group_id TEXT REFERENCES category_groups(id),
  name TEXT NOT NULL,
  hidden SMALLINT NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1)),
  internal SMALLINT NOT NULL DEFAULT 0 CHECK (internal IN (0, 1)),
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_categories_plan_id ON categories(plan_id);
CREATE INDEX IF NOT EXISTS idx_categories_group_id ON categories(category_group_id);

CREATE TABLE IF NOT EXISTS payees (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  transfer_account_id TEXT,
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(plan_id, name)
);

CREATE INDEX IF NOT EXISTS idx_payees_plan_id ON payees(plan_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payees_plan_transfer_account
  ON payees(plan_id, transfer_account_id) WHERE transfer_account_id IS NOT NULL AND deleted = 0;

CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,
  ledger_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  amount_milli BIGINT NOT NULL,
  memo TEXT,
  cleared TEXT NOT NULL DEFAULT 'uncleared',
  approved SMALLINT NOT NULL DEFAULT 0 CHECK (approved IN (0, 1)),
  flag_color TEXT,
  flag_name TEXT,
  payee_id TEXT REFERENCES payees(id) ON DELETE SET NULL,
  payee_name_snapshot TEXT,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  category_name_snapshot TEXT,
  transfer_account_id TEXT,
  transfer_transaction_id TEXT,
  matched_transaction_id TEXT,
  import_id TEXT,
  import_payee_name TEXT,
  import_payee_name_original TEXT,
  source_kind TEXT,
  source_ref TEXT,
  external_ynab_id TEXT,
  server_knowledge BIGINT NOT NULL DEFAULT 1,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_transactions_plan_date ON transactions(plan_id, date);
CREATE INDEX IF NOT EXISTS idx_transactions_account_date ON transactions(account_id, date);
CREATE INDEX IF NOT EXISTS idx_transactions_payee_id ON transactions(payee_id);
CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_import_id ON transactions(plan_id, import_id);
CREATE INDEX IF NOT EXISTS idx_transactions_plan_server_knowledge ON transactions(plan_id, server_knowledge);

CREATE TABLE IF NOT EXISTS subtransactions (
  id TEXT PRIMARY KEY,
  ledger_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  amount_milli BIGINT NOT NULL,
  memo TEXT,
  payee_id TEXT REFERENCES payees(id) ON DELETE SET NULL,
  payee_name_snapshot TEXT,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  category_name_snapshot TEXT,
  transfer_account_id TEXT,
  transfer_transaction_id TEXT,
  external_ynab_id TEXT,
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_subtransactions_transaction_id ON subtransactions(transaction_id);

CREATE TABLE IF NOT EXISTS source_events (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  transaction_id TEXT REFERENCES transactions(id) ON DELETE SET NULL,
  source_kind TEXT NOT NULL,
  source_ref TEXT,
  source_provider TEXT,
  payload_json TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_source_events_transaction_id ON source_events(transaction_id);

CREATE TABLE IF NOT EXISTS import_sessions (
  id TEXT PRIMARY KEY,
  plan_id TEXT REFERENCES plans(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  started_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  finished_at TEXT,
  summary_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS import_rows (
  id TEXT PRIMARY KEY,
  import_session_id TEXT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
  row_index INTEGER NOT NULL,
  status TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  error TEXT,
  transaction_id TEXT REFERENCES transactions(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_import_rows_session ON import_rows(import_session_id, row_index);

CREATE TABLE IF NOT EXISTS ynab_sync_state (
  plan_id TEXT PRIMARY KEY REFERENCES plans(id) ON DELETE CASCADE,
  server_knowledge BIGINT NOT NULL DEFAULT 0,
  lease_id TEXT,
  lease_until TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_runs (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  scheduled_for TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMPTZ,
  result_json JSONB NOT NULL DEFAULT '{}',
  error TEXT,
  UNIQUE(plan_id, scheduled_for)
);

CREATE INDEX IF NOT EXISTS idx_sync_runs_plan_started ON sync_runs(plan_id, started_at DESC);

CREATE TABLE IF NOT EXISTS audit_events (
  id TEXT PRIMARY KEY,
  plan_id TEXT REFERENCES plans(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  source TEXT NOT NULL,
  metadata_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_events_plan_created ON audit_events(plan_id, created_at DESC);
