import { Database } from "bun:sqlite";
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { assertInactiveTarget, generateChunks, reconcileCheckpoints, reconcileRun } from "./lib/d1-ledger-import";
import { buildVerification, compareVerification } from "./lib/d1-ledger-verify";
function fixture(){const db=new Database(":memory:"); for(const path of ["apps/api/migrations/001_initial.sql","apps/api/migrations/002_transaction_server_knowledge.sql","apps/api/migrations/003_transfer_payees.sql"])db.exec(readFileSync(path,"utf8")); db.exec("INSERT INTO plans(id,name) VALUES('p','P'); INSERT INTO accounts(id,plan_id,name,balance_milli,cleared_balance_milli,uncleared_balance_milli) VALUES('a','p','A',5,0,5); INSERT INTO transactions(id,plan_id,account_id,date,amount_milli,deleted,cleared) VALUES('t','p','a','2026-01-01',5,0,'uncleared')"); db.exec(readFileSync("apps/api/migrations/003_transfer_payees.sql","utf8")); return db;}
describe("inactive D1 ledger tools",()=>{
 test("chunks are deterministic, bounded, explicit and collisions fail",()=>{const db=fixture(), a:any[]=[],b:any[]=[]; generateChunks(db,"abc","run",{maxRows:1,maxBytes:10000},(s,c)=>a.push([s,c])); generateChunks(db,"abc","run",{maxRows:1,maxBytes:10000},(s,c)=>b.push([s,c])); expect(a).toEqual(b); expect(a.flatMap(x=>x[0]).join()).not.toContain("OR IGNORE"); expect(a[0][0]).not.toContain("BEGIN"); expect(a.every(([sql])=>Buffer.byteLength(sql)<=10000)).toBeTrue(); expect(()=>db.run("INSERT INTO plans VALUES ('p','collision')")).toThrow(); db.close();});
 test("resume rejects disagreement",()=>{const c:any={source_sha256:"x",table_name:"plans",chunk_number:0,row_count:1,chunk_sha256:"h",first_stable_key:"a",last_stable_key:"a"}; expect(reconcileCheckpoints([c],[c]).size).toBe(1); expect(()=>reconcileCheckpoints([c],[{...c,chunk_sha256:"bad"}])).toThrow("disagreement");});
 test("resume binds the destination run to exact source bytes and chunk count",()=>{const expected={id:"run",source_sha256:"abc",source_bytes:12,expected_chunk_count:4}; expect(reconcileRun(expected,[])).toBeNull(); expect(reconcileRun(expected,[{...expected,status:"running"}])).toEqual({...expected,status:"running"}); expect(()=>reconcileRun(expected,[{...expected,source_bytes:13,status:"running"}])).toThrow("different source"); expect(()=>reconcileRun(expected,[{...expected,expected_chunk_count:3,status:"running"}])).toThrow("different source"); expect(()=>reconcileRun(expected,[{...expected,status:"running"},{...expected,status:"complete"}])).toThrow("multiple");});
 test("target guard requires exact inactive identity",()=>{const id="12345678-1234-1234-1234-123456789abc"; expect(()=>assertInactiveTarget("howmuch",id,"")).toThrow(); expect(()=>assertInactiveTarget("ledger-INACTIVE",id,"wrong")).toThrow(); expect(()=>assertInactiveTarget("ledger-INACTIVE",id,`INACTIVE ledger-INACTIVE ${id}`)).not.toThrow();});
 test("verification reports row and missing-provenance mismatches",()=>{const a=fixture(), b=fixture(); b.exec("UPDATE transactions SET amount_milli=6"); expect(compareVerification(buildVerification(a),buildVerification(b))).toContain("logical source hash mismatch"); a.close();b.close();});
});
